import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import CSSRuntimeProvider from '@master/css.react'
import config from '../../master.css'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={process.env.NODE_ENV === 'development' ? { display: 'none' } : undefined}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CSSRuntimeProvider config={config}>
          {children}
        </CSSRuntimeProvider>
      </body>
    </html>
  );
}
